AllCops:
  DisplayCopNames: true

Lint/EndAlignment:
  EnforcedStyleAlignWith: "start_of_line"

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Lint/UnneededSplatExpansion:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
    - "context"
    - "define"
    - "describe"
    - "let"
    - "it"

Metrics/LineLength:
  Max: 160

Style/AlignParameters:
  EnforcedStyle: "with_fixed_indentation"

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/CaseIndentation:
  EnforcedStyle: "end"

Style/ClosingParenthesisIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/EmptyElse:
  EnforcedStyle: "empty"

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: "empty_lines_except_namespace"

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: "empty_lines_except_namespace"

Style/FirstParameterIndentation:
  EnforcedStyle: "consistent"

Style/GuardClause:
  MinBodyLength: 2

Style/HashSyntax:
  EnforcedStyle: "ruby19_no_mixed_keys"

Style/IndentArray:
  EnforcedStyle: "consistent"

Style/IndentHash:
  EnforcedStyle: "consistent"

Style/Lambda:
  EnforcedStyle: "literal"

Style/MultilineMethodCallIndentation:
  EnforcedStyle: "indented"

Style/MultilineOperationIndentation:
  EnforcedStyle: "indented"

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: "zero_only"

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "[]"
    "%w": "[]"
    "%W": "[]"
    "%x": "{}"

Style/StringLiterals:
  EnforcedStyle: "double_quotes"

Style/TernaryParentheses:
  EnforcedStyle: "require_parentheses_when_complex"

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: "comma"

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: "comma"
